/**
 * useLanguage — provides all UI copy strings in Tamil, English, and Hindi.
 *
 * This is an in-memory constant map — no translation library needed.
 * All strings are written to be simple and suitable for elderly users.
 */

export const STRINGS = {
  en: {
    appName: 'ScreenSaathi',
    tagline: 'Your helpful screen companion 🙏',
    showScreen: '📸 Show Your Screen',
    undoMe: '↩ What Did I Just Do?',
    changeLanguage: 'Change Language',
    analyzing: 'Looking at your screen…',
    analyzingSubtext: 'Please wait, one moment 🙏',
    cancel: 'Cancel',
    reassurance: 'Reassurance',
    whatItMeans: 'What this screen means',
    whatToDo: 'What to do now →',
    readAloud: '🔊 Read Aloud',
    stopReading: '⏸ Stop',
    notifyFamily: '📞 Notify My Family',
    tryAgain: '📸 Try Another Screen',
    goHome: '🏠 Go Back Home',
    scamWarningTitle: '⚠️ Wait — Let\'s Check This Together',
    scamWarningSubtext: 'This screen looks suspicious. Do not enter any information yet.',
    callBank: '📞 Call Bank Helpline',
    escalationTitle: "I'm Not Sure About This Screen",
    escalationSubtext: "I don't want to give you wrong advice. Here's what to do instead:",
    callFamily: '📞 Call a Family Member',
    tryBetterPhoto: '📸 Take a Clearer Photo',
    notifyFamilyTitle: 'Notify Your Family',
    notifyFamilyDesc: 'We will send them a short message. Your screenshot will NOT be shared.',
    contactEmail: 'Family Email',
    contactPhone: 'Family Phone Number',
    send: 'Send Message',
    sending: 'Sending…',
    notifySent: '✅ Your family has been notified.',
    notifyError: 'Could not send. Please try again.',
    consentTitle: 'Before we start',
    consentText: 'ScreenSaathi helps you understand confusing screens. Your screenshots are analyzed and immediately deleted — never stored. We will never share your information.',
    consentButton: 'I Understand — Let\'s Begin',
    errorTitle: 'Something went wrong',
    retry: 'Try Again',
    undomeTitle: 'Here is what happened',
    undomeSubtext: 'You are safe. Nothing bad has happened.',
    bankHelpline: '1800-XXX-XXXX',
    confidenceLabel: 'Confidence',
    imageTooLarge: 'Image too large. Please use a screenshot under 5 MB.',
    invalidFile: 'Please upload a photo or screenshot (JPEG, PNG, or WEBP).',
    noInternet: 'No internet connection. Please check your WiFi.',
  },
  ta: {
    appName: 'ScreenSaathi',
    tagline: 'உங்கள் திரை உதவியாளர் 🙏',
    showScreen: '📸 உங்கள் திரையைக் காட்டுங்கள்',
    undoMe: '↩ நான் என்ன செய்தேன்?',
    changeLanguage: 'மொழி மாற்று',
    analyzing: 'உங்கள் திரையைப் பார்க்கிறேன்…',
    analyzingSubtext: 'ஒரு நிமிடம் காத்திருங்கள் 🙏',
    cancel: 'ரத்துசெய்',
    reassurance: 'அமைதி',
    whatItMeans: 'இந்த திரை என்ன சொல்கிறது',
    whatToDo: 'இப்போது என்ன செய்ய வேண்டும் →',
    readAloud: '🔊 声に出して読む',
    stopReading: '⏸ நிறுத்து',
    notifyFamily: '📞 குடும்பத்தினரை அறிவிக்கவும்',
    tryAgain: '📸 மீண்டும் முயற்சிக்கவும்',
    goHome: '🏠 முகப்புக்கு திரும்பு',
    scamWarningTitle: '⚠️ நில்லுங்கள் — சேர்ந்து சரிபார்ப்போம்',
    scamWarningSubtext: 'இந்த திரை சந்தேகமாக உள்ளது. எந்த தகவலையும் உள்ளிட வேண்டாம்.',
    callBank: '📞 வங்கி helpline அழைக்கவும்',
    escalationTitle: 'இந்த திரையில் எனக்கு உறுதியில்லை',
    escalationSubtext: 'தவறான ஆலோசனை தர விரும்பவில்லை. இதை செய்யுங்கள்:',
    callFamily: '📞 குடும்பத்தினரை அழையுங்கள்',
    tryBetterPhoto: '📸 தெளிவான படம் எடுங்கள்',
    notifyFamilyTitle: 'குடும்பத்தினரை அறிவிக்கவும்',
    notifyFamilyDesc: 'அவர்களுக்கு ஒரு சிறு செய்தி அனுப்புவோம். உங்கள் screenshot பகிரப்படாது.',
    contactEmail: 'குடும்ப மின்னஞ்சல்',
    contactPhone: 'குடும்ப தொலைபேசி எண்',
    send: 'செய்தி அனுப்பு',
    sending: 'அனுப்புகிறேன்…',
    notifySent: '✅ குடும்பத்தினர் அறிவிக்கப்பட்டனர்.',
    notifyError: 'அனுப்ப முடியவில்லை. மீண்டும் முயற்சிக்கவும்.',
    consentTitle: 'தொடங்குவதற்கு முன்',
    consentText: 'ScreenSaathi உங்களுக்கு திரைகளை புரிந்துகொள்ள உதவுகிறது. உங்கள் screenshots பகுப்பாய்வு செய்யப்பட்டு உடனடியாக அழிக்கப்படும் — சேமிக்கப்படாது.',
    consentButton: 'புரிந்தது — தொடங்குவோம்',
    errorTitle: 'ஏதோ தவறு நடந்தது',
    retry: 'மீண்டும் முயற்சிக்கவும்',
    undomeTitle: 'என்ன நடந்தது என்று பாருங்கள்',
    undomeSubtext: 'நீங்கள் பாதுகாப்பாக இருக்கிறீர்கள். கவலைப்படாதீர்கள்.',
    bankHelpline: '1800-XXX-XXXX',
    confidenceLabel: 'நம்பகத்தன்மை',
    imageTooLarge: 'படம் மிகவும் பெரியது. 5 MB-க்கும் குறைவான படம் பயன்படுத்துங்கள்.',
    invalidFile: 'JPEG, PNG, அல்லது WEBP படம் பதிவேற்றவும்.',
    noInternet: 'இணைய இணைப்பு இல்லை. WiFi சரிபார்க்கவும்.',
  },
  hi: {
    appName: 'ScreenSaathi',
    tagline: 'आपका स्क्रीन साथी 🙏',
    showScreen: '📸 अपनी स्क्रीन दिखाएं',
    undoMe: '↩ मैंने अभी क्या किया?',
    changeLanguage: 'भाषा बदलें',
    analyzing: 'आपकी स्क्रीन देख रहे हैं…',
    analyzingSubtext: 'कृपया एक पल प्रतीक्षा करें 🙏',
    cancel: 'रद्द करें',
    reassurance: 'राहत',
    whatItMeans: 'यह स्क्रीन क्या कह रही है',
    whatToDo: 'अभी क्या करें →',
    readAloud: '🔊 ज़ोर से पढ़ें',
    stopReading: '⏸ रोकें',
    notifyFamily: '📞 परिवार को सूचित करें',
    tryAgain: '📸 दूसरी स्क्रीन दिखाएं',
    goHome: '🏠 घर वापस जाएं',
    scamWarningTitle: '⚠️ रुकिए — साथ मिलकर जांचते हैं',
    scamWarningSubtext: 'यह स्क्रीन संदिग्ध लग रही है। कोई जानकारी दर्ज न करें।',
    callBank: '📞 बैंक हेल्पलाइन कॉल करें',
    escalationTitle: 'मुझे इस स्क्रीन के बारे में पूरी जानकारी नहीं',
    escalationSubtext: 'मैं गलत सलाह नहीं देना चाहता। इसके बजाय यह करें:',
    callFamily: '📞 परिवार को फ़ोन करें',
    tryBetterPhoto: '📸 साफ़ फ़ोटो लें',
    notifyFamilyTitle: 'परिवार को सूचित करें',
    notifyFamilyDesc: 'उन्हें एक छोटा संदेश भेजेंगे। आपका screenshot साझा नहीं किया जाएगा।',
    contactEmail: 'परिवार का ईमेल',
    contactPhone: 'परिवार का फ़ोन नंबर',
    send: 'संदेश भेजें',
    sending: 'भेज रहे हैं…',
    notifySent: '✅ आपके परिवार को सूचित कर दिया गया।',
    notifyError: 'भेज नहीं सका। दोबारा कोशिश करें।',
    consentTitle: 'शुरू करने से पहले',
    consentText: 'ScreenSaathi आपको स्क्रीन समझने में मदद करता है। आपके screenshots का विश्लेषण होता है और तुरंत हटा दिया जाता है — कभी सेव नहीं किया जाता।',
    consentButton: 'समझ गया — चलिए शुरू करते हैं',
    errorTitle: 'कुछ गलत हो गया',
    retry: 'फिर कोशिश करें',
    undomeTitle: 'देखिए क्या हुआ',
    undomeSubtext: 'आप सुरक्षित हैं। कोई बुरी बात नहीं हुई।',
    bankHelpline: '1800-XXX-XXXX',
    confidenceLabel: 'विश्वसनीयता',
    imageTooLarge: 'छवि बहुत बड़ी है। 5 MB से कम का screenshot उपयोग करें।',
    invalidFile: 'कृपया JPEG, PNG, या WEBP फ़ोटो अपलोड करें।',
    noInternet: 'इंटरनेट नहीं है। WiFi जांचें।',
  },
};

/**
 * Returns the string map for the given language, falling back to English.
 */
export function useLanguage(language) {
  return STRINGS[language] || STRINGS.en;
}
